module.exports = {
	extends: ['stylelint-config-recommended', 'stylelint-config-prettier'],
	plugins: [
		'stylelint-prettier',
		'stylelint-declaration-strict-value',
		'stylelint-high-performance-animation',
		'stylelint-selector-tag-no-without-class',
		'stylelint-order',
	],
	rules: {
		'prettier/prettier': true,
		'at-rule-no-unknown': [true, { ignoreAtRules: ['mixin', 'define-mixin'] }],
		'selector-pseudo-class-no-unknown': [true, { ignorePseudoClasses: ['global'] }],
		'color-no-hex': true,
		'unit-whitelist': ['px', 'deg', '%', 's', 'vw', 'vh'],
		'property-blacklist': ['font-size', 'font-family', 'font-weight', 'line-height'],
		'shorthand-property-no-redundant-values': true,
		'value-no-vendor-prefix': true,
		'property-no-vendor-prefix': true,
		'declaration-block-no-redundant-longhand-properties': true,
		'declaration-no-important': true,
		'selector-no-vendor-prefix': true,
		'at-rule-no-vendor-prefix': true,
		'max-nesting-depth': 3,
		'no-unknown-animations': true,
		'scale-unlimited/declaration-strict-value': 'color',
		'plugin/no-low-performance-animation-properties': true,
		'plugin/selector-tag-no-without-class': ['/^(?!.*(path|rect|circle))/'],
		'order/order': [
			'custom-properties',
			{
				type: 'at-rule',
				name: 'mixin',
				hasBlock: false,
			},
			'declarations',
			{
				type: 'at-rule',
				name: 'media',
				hasBlock: true,
			},
			'rules',
		],
		'order/properties-order': [
			[
				'position',
				'display',
				'float',
				'z-index',
				'content',
				'text-align',
				'cursor',
				'user-select',
				'text-decoration',
				'pointer-events',
				'color',
				'background',
				'fill',
				'stroke',
				'box-shadow',
				'opacity',
				'stroke-width',
				'min-width',
				'width',
				'max-width',
				'min-height',
				'height',
				'max-height',
				'flex-basis',
				'top',
				'right',
				'left',
				'bottom',
				'margin',
				'margin-top',
				'margin-right',
				'margin-bottom',
				'margin-left',
				'padding',
				'padding-top',
				'padding-right',
				'padding-bottom',
				'padding-left',
				'border',
				'border-top',
				'border-right',
				'border-bottom',
				'border-left',
				'transform',
				'transition',
				'animation',
			],
			{
				unspecified: 'bottomAlphabetical',
			},
		],
	},
};
